sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dschuema/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dschuema/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-west-2-212522758076"
  bucket_path: "docker-react-test"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
