sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dschuema/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dschuema/docker-react npm run test