name: docker-react
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Test Image
      run: docker build -t dschuemann/docker-react -f Dockerfile.dev .
    - name: Test Image
      run: docker run -e CI=true dschuemann/docker-react npm run test