name: docker-react
on: push

jobs:
  Build:
    name: Build and Test Image
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Build Test Image
      run: docker build -t dschuemann/docker-react -f Dockerfile.dev .
    
    - name: Test Image
      run: docker run -e CI=true dschuemann/docker-react npm run test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Upload file 'DEPLOY.ZIP' as an artifact
      uses: actions/upload-artifact@v1
      with:
          name: deploy.zip
          path: deploy.zip
  
  Push_to_registry:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: Build_and_Test_image

    steps:

      # - name: Check out the repo
      #   uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dschuemann/docker-react:latest

  Deploy_on_EBS:

    runs-on: ubuntu-latest
    needs: [Build, Push_to_registry]

    steps:

    - name: Download file 'DEPLOY.ZIP' from artifact
      uses: actions/download-artifact@v1
      with:
        name: deploy.zip

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react-test
        environment_name: DockerReactTest-env
        version_label: 1.0
        region: us-west-2
        deployment_package: deploy.zip
        use_existing_version_if_available: true

