name: docker-react
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Test Image
      run: docker build -t dschuemann/docker-react -f Dockerfile.dev .
    
    - name: Test Image
      run: docker run -e CI=true dschuemann/docker-react npm run test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

  Deploy:

    runs-on: ubuntu-latest
    
    steps:  
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react-test
        environment_name: DockerReactTest-env
        version_label: 1.0
        region: us-west-2
        deployment_package: deploy.zip


