name: docker-react
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Test Image
      run: docker build -t dschuema/docker-react -f Dockerfile.dev .
    - name: Test Image
      run: docker run -e CI=true dschuema/docker-react npm run test